
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Pikabu
DISPLAY_NAME = Pikabu
BUNDLE_ID = com.jeffreychan.pikabu

Pikabu_FILES = Tweak.xm PikabuView.m PikabuController.m PikabuSliderView.m PikabuBaseView.m Pikabu.m PikabuImageView.m
Pikabu_IPA = /Users/jeffrey/jailbreak_tweaks
Pikabu_FRAMEWORKS = CoreGraphics QuartzCore Foundation AVFoundation AudioToolbox
Pikabu_LIBRARIES = substrate
Pikabu_CFLAGS = -I../include

include $(THEOS_MAKE_PATH)/tweak.mk
